import reflex as rx
import datetime

tiempo = datetime.datetime.now()

def tabla(title: str, body: str) -> rx.Component:
    return rx.flex(
        rx.heading(title),
        rx.table.root(
    rx.table.header(
        rx.table.row(
            rx.table.column_header_cell(""),
            rx.table.column_header_cell(tiempo.day,col_span="2"),
            rx.table.column_header_cell(tiempo.day +1,col_span="2"),
            rx.table.column_header_cell(tiempo.day +2,col_span="2"),
            rx.table.column_header_cell(tiempo.day +3,col_span="2"),
            rx.table.column_header_cell(tiempo.day +4,col_span="2"),
            rx.table.column_header_cell(tiempo.day +5,col_span="2"),
            rx.table.column_header_cell(tiempo.day +6,col_span="2"),
            rx.table.column_header_cell(tiempo.day +7,col_span="2"),
            rx.table.column_header_cell(tiempo.day +8,col_span="2"),
            rx.table.column_header_cell(tiempo.day +9,col_span="2"),
            rx.table.column_header_cell(tiempo.day +10,col_span="2"),
            rx.table.column_header_cell(tiempo.day +11,col_span="2"),
            rx.table.column_header_cell(tiempo.day +12,col_span="2"),
            rx.table.column_header_cell(tiempo.day +13,col_span="2"),
            rx.table.column_header_cell(tiempo.day +14,col_span="2"),
            rx.table.column_header_cell(tiempo.day +15,col_span="2"),
            rx.table.column_header_cell(tiempo.day +16,col_span="2"),
            rx.table.column_header_cell(tiempo.day +17,col_span="2"),
            rx.table.column_header_cell(tiempo.day +18,col_span="2"),
            rx.table.column_header_cell(tiempo.day +19,col_span="2"),
            rx.table.column_header_cell(tiempo.day +20,col_span="2"),
            rx.table.column_header_cell(tiempo.day +21,col_span="2"),
            rx.table.column_header_cell(tiempo.day +22,col_span="2"),
            rx.table.column_header_cell(tiempo.day +23,col_span="2"),
            rx.table.column_header_cell(tiempo.day +24,col_span="2"),
        ),
        ),
    rx.table.body(
        rx.table.row(
            rx.table.row_header_cell(""),
            rx.table.cell("Id"),
            rx.table.cell("Nombre"),
            rx.table.cell("Id"),
            rx.table.cell("Nombre"),
            rx.table.cell("Id"),
            rx.table.cell("Nombre"),
            rx.table.cell("Id"),
            rx.table.cell("Nombre"),
            rx.table.cell("Id"),
            rx.table.cell("Nombre"),
        ),
        rx.table.row(
            rx.table.row_header_cell("M",row_span="3"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),             
        ),
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),      
          
        rx.table.row(
            rx.table.row_header_cell("T", row_span="3"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),    
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),    
        rx.table.row(
            rx.table.row_header_cell("N", row_span="3"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),
        rx.table.row(
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),
            rx.table.cell("4567"),
            rx.table.cell("Juan"),            
        ),
                     
    ),
    size="3",
    variant="surface",


    ),
    direction="column",
    spacing="4",
)    
    